{% set name = "cmip-basins" %}
{% set version = "1.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmip_basins-{{ version }}.tar.gz"

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python>=3.6
    - xarray>=0.16.1
    - numpy
    - regionmask

about:
  home: https://github.com/jkrasting/cmip_basins
  license: Public Domain
  summary: "Generate CMIP-style ocean basin masks"

extra:
  recipe-maintainers:
    - jkrasting
