{% set data = load_setup_py_data() %}

package:
  name: cmip-basins
  version: {{ data['version'] }}

source:
  path: ..

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python>=3.6
    - xarray>=0.16.0
    - numpy>=1.17
    - regionmask
  run:
    - python>=3.6
    - xarray>=0.16.0
    - numpy>=1.17
    - regionmask

about:
  home: https://github.com/jkrasting/cmip_basins
  license: Public Domain
  summary: "Generate CMIP-style ocean basin masks"
